package us.teaminceptus.silverskillz.premium;

class License {

	// This class exists to prevent cracked versions being downloaded via the opensource github. When a project is uploaded, the JAR contains this class, but it is not on the GitHub.

	protected static final String LICENSE_KEY = "ZG9uJ3QgZGlzdHJpYnV0ZSB0aGUgbGljZW5zZSBvciBiYWQKbmV2ZXIgZ29ubmEgZ2l2ZSB5b3UgdXAKbmV2ZXIgZ29ubmEgbGV0IHlvdSBkb3duCm5ldmVyIGdvbm5hIHJ1biBhcm91bmQgYW5kIGRlc2VydCB5b3UKbmV2ZXIgZ29ubmEgbWFrZSB5b3UgY3J5Cm5ldmVyIGdvbm5hIHNheSBnb29kYnllCm5ldmVyIGdvbm5hIHRlbGwgYSBsaWUgYW5kIGh1cnQgeW91Cgp3aHkgYXJlIHlvdSBkZWNvZGluZyB0aGlzLCBpdCdzIGxpa2Ugc3VwZXIgdW5uZWNlc3NhcnkKbGlrZSB3aHkKCmFueXdheXMgZ3Vlc3Mgd2UnbGwgdGFsayBhYm91dCByYW5kb20gY3JhcAoKdGhlIGRpc2NvcmQgaXMgaHR0cHM6Ly9kaXNjb3JkLmlvL3RoZW5vb2J5Z29kcwoKam9pbiBpZiB5b3UgYXJlIGNvb2wKc3Vic2NyaWJlIHRvIGx1bmF0b2NpdHkgYW5kIHJhbmV0ZXIKdGhhbmsgeW91IGZvciBidXlpbmcgdGhlIHBsdWdpbiA6KQ==";
}